# ----------------------------------------------------------------------------
#
# Package             : jitsi-sctp
# Source Repo         : https://github.com/jitsi/jitsi-sctp
# Travis Job Link     : https://travis-ci.com/github/asellappen/jitsi-sctp/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: '12'

    - os: linux
      dist: bionic
      sudo: true
      language: node_js
      node_js: '12'
      addons:
        apt:
          packages:
            - libx11-dev
            - zlib1g-dev
            - libpng-dev
            - libxtst-dev

script:
  - npm run dist
