# ----------------------------------------------------------------------------
#
# Package             : jitsi-sctp
# Source Repo         : https://github.com/jitsi/jitsi-sctp
# Travis Job Link     : https://travis-ci.com/github/asellappen/jitsi-sctp/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com>/Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

sudo: false
language: java

dist: bionic 

arch:
  - amd64
  - ppc64le

script:
   - mvn package
   - mvn test
 # - mvn install
 # - mvn package -DbuildSctp -DbuildNativeWrapper -DdeployNewJnilib
 # - mvn install -DbuildSctp -DbuildNativeWrapper -DdeployNewJnilib
